--Remove when in v0.00
IF OBJECT_ID (N'Service', N'U') IS NOT NULL 
   DROP TABLE [Service]

CREATE TABLE [Service]
(
[Id] BIGINT NOT NULL,
[Name] NVARCHAR(255),
[Price] DECIMAL(18,4) NOT NULL,
[Currency] NVARCHAR(3) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [Service] ADD CONSTRAINT [UC_Name] UNIQUE ([Name])
