CREATE TABLE [Discount]
(
[Id] BIGINT NOT NULL,
[AssignedServiceId] BIGINT NOT NULL,
[Percentage] DECIMAL(3,2) NOT NULL,
[ValidFrom] DATE NULL,
[ValidTo] DATE NULL,
CONSTRAINT [PK_Discount] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [Discount] ADD CONSTRAINT [FK_AssignedServiceId_AssignedService] FOREIGN KEY ([AssignedServiceId]) REFERENCES [AssignedService](Id)


