CREATE TABLE [AssignedService]
(
[Id] BIGINT NOT NULL,
[ServiceId] BIGINT NOT NULL,
[ServiceName] NVARCHAR(255) NULL,
[CustomerId] BIGINT NOT NULL,
CONSTRAINT [PK_AssignedService] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [AssignedService] ADD CONSTRAINT [FK_CustomerId_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [Customer](Id)


